### ISSUE TITLE
error: terminated(72): xcrun --sdk macosx --find xctest 

### ISSUE THREAD

**Issue by shiny** [mxcl/homebrew-made#1]
```shell
brew install mxcl/made/swift-sh

==> Installing swift-sh from mxcl/made
==> Cloning https://github.com/mxcl/swift-sh
Updating /Users/daijie/Library/Caches/Homebrew/swift-sh--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 2a223fc .some
==> swift build --configuration release -Xswiftc -static-stdlib --disable-sandbo
Last 15 lines from /Users/daijie/Library/Logs/Homebrew/swift-sh/01.swift:
2019-01-12 19:26:46 +0800

swift
build
--configuration
release
-Xswiftc
-static-stdlib
--disable-sandbox

error: terminated(72): xcrun --sdk macosx --find xctest output:



If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mxcl/homebrew-made/issues
```

```shell
xcrun --sdk macosx --find xctest
xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
```

**Comment by mxcl** [comment]
I need the full logs. But looks like something is broken with your Xcode installation to me.

**Comment by shiny** [comment]
This log is full.
I've also tried `brew install --verbose --debug mxcl/made/swift-sh`
Here is the log:
```
➜  ~ brew install --verbose --debug mxcl/made/swift-sh

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/mxcl/homebrew-made/swift-sh.rb
==> Installing swift-sh from mxcl/made
/usr/bin/sandbox-exec -f /private/tmp/homebrew20190112-13451-1bmvfm7.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.62.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib:/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin18:/Library/Ruby/Site/2.3.0/universal-darwin18:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/mxcl/homebrew-made/swift-sh.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mxcl/homebrew-made/swift-sh.rb
==> Cloning https://github.com/mxcl/swift-sh
git --git-dir /Users/daijie/Library/Caches/Homebrew/swift-sh--git/.git status -s
Updating /Users/daijie/Library/Caches/Homebrew/swift-sh--git
git config remote.origin.url https://github.com/mxcl/swift-sh
git config remote.origin.fetch \+refs/heads/master:refs/remotes/origin/master
git config remote.origin.tagOpt --no-tags
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up to date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 2a223fc .some
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/Tests/. /private/tmp/d20190112-13452-1je5zwe/Tests
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/README.md /private/tmp/d20190112-13452-1je5zwe/README.md
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/.gitignore /private/tmp/d20190112-13452-1je5zwe/.gitignore
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/Package.swift /private/tmp/d20190112-13452-1je5zwe/Package.swift
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/Sources/. /private/tmp/d20190112-13452-1je5zwe/Sources
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/.git/. /private/tmp/d20190112-13452-1je5zwe/.git
cp -pR /Users/daijie/Library/Caches/Homebrew/swift-sh--git/main.swift /private/tmp/d20190112-13452-1je5zwe/main.swift
cp -pR /private/tmp/d20190112-13452-1je5zwe/Tests/. /private/tmp/swift-sh-20190112-13452-gibbm8/Tests
cp -pR /private/tmp/d20190112-13452-1je5zwe/README.md /private/tmp/swift-sh-20190112-13452-gibbm8/README.md
cp -pR /private/tmp/d20190112-13452-1je5zwe/.gitignore /private/tmp/swift-sh-20190112-13452-gibbm8/.gitignore
cp -pR /private/tmp/d20190112-13452-1je5zwe/Package.swift /private/tmp/swift-sh-20190112-13452-gibbm8/Package.swift
cp -pR /private/tmp/d20190112-13452-1je5zwe/Sources/. /private/tmp/swift-sh-20190112-13452-gibbm8/Sources
cp -pR /private/tmp/d20190112-13452-1je5zwe/.git/. /private/tmp/swift-sh-20190112-13452-gibbm8/.git
cp -pR /private/tmp/d20190112-13452-1je5zwe/main.swift /private/tmp/swift-sh-20190112-13452-gibbm8/main.swift
chmod -Rf +w /private/tmp/d20190112-13452-1je5zwe
git --git-dir /Users/daijie/Library/Caches/Homebrew/swift-sh--git/.git show -s --format=\%cD
==> swift build --configuration release -Xswiftc -static-stdlib --disable-sandbox
error: terminated(72): xcrun --sdk macosx --find xctest output:


/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: swift build --configuration release -Xswiftc -static-stdlib --disable-sandbox
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: Error: An exception occurred within a child process:
  SystemExit: exit
/usr/local/Homebrew/Library/Homebrew/debrew.rb:56:in `exit'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:56:in `choose'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:112:in `block in debug'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:111:in `loop'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:111:in `debug'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:14:in `rescue in raise'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:10:in `raise'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1921:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1858:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1858:in `system'
/usr/local/Homebrew/Library/Taps/mxcl/homebrew-made/swift-sh.rb:9:in `install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:92:in `debrew'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:143:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1136:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2055:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:536:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2054:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:103:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:173:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2030:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1131:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:536:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
➜  ~
```

**Comment by mxcl** [comment]
Hi, the original log stated: `Last 15 lines from /Users/daijie/Library/Logs/Homebrew/swift-sh/01.swift:`

Please provide the full log, and the output from `brew --env`. You should also fix any errors `brew doctor` says as usual.

**Comment by shiny** [comment]
I reinstalled the homebrew, now swift sh is on my mac but when i run the demo ./script
it shows 
![image](https://user-images.githubusercontent.com/117487/51075159-eb614e00-16c2-11e9-86c8-5e321579a90b.png)


![image](https://user-images.githubusercontent.com/117487/51075162-f1572f00-16c2-11e9-9d17-cd0c471da098.png)

**Comment by mxcl** [comment]
It appears that SwiftPM itself is unable to function.

This Google may help: 
https://www.google.com/search?client=safari&rls=en&q=xcrun+--sdk+macosx+--find+xctest+output&ie=UTF-8&oe=UTF-8

**Comment by mxcl** [comment]
Most suggestions seem to imply your `xcode-select` path is wrong. You could do the common suggestion of:

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by shiny** [comment]
> Most suggestions seem to imply your `xcode-select` path is wrong. You could do the common suggestion of:
> 
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

Cool, it's working now hahahaha
Thank you!

**Comment by mxcl** [comment]
Glad to hear.

If you found my help useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl).

**Comment by kornerr** [comment]
I've just had the same error when running `mint run xcodegen` while using Mintfile.

@mxcl's answer did help:
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by PeterKaminski09** [comment]
> Most suggestions seem to imply your xcode-select path is wrong. You could do the common suggestion of:
> 
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

I've found that 
`sudo xcode-select -r` will reset the path to /Applications/Xcode.app/Contents/Developer
You can run `sudo xcode-select -p` to show the current path.

http://iosdevelopertips.com/xcode/xcode-select-managing-multiple-versions-of-xcode.html

**Comment by Acshu-tech** [comment]
> Most suggestions seem to imply your `xcode-select` path is wrong. You could do the common suggestion of:
> 
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

You really saved my day, thank you!
